# contract used in release workflow
apiVersion: chainloop.dev/v1
kind: Contract
metadata:
  name: chainloop-chainloop-github-release
  description: Contract for Chainloop GitHub release workflow
spec:
  policies:
    attestation:
      - ref: source-commit
        with:
          check_signature: yes
          check_author_verified: yes
        requirements:
          - chainloop-best-practices/source-commit-attestation
  policyGroups:
    - ref: slsa-checks
      with:
        runner: GITHUB_ACTION
